---
title: "Negative Binomial Regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE,warning=FALSE}
library(tidyverse)
library(MASS)
library(knitr)
```

### Number of Days Absent

```{r}
daysAbs <- read.csv("https://raw.githubusercontent.com/RWorkshop/workshopdatasets/master/negbin.csv")
daysAbs <- daysAbs %>% mutate(prog=as.factor(prog))
head(daysAbs) %>% kable()
```

```{r}
summary(daysAbs)
```

### Checking Dispersion

```{r}

# Checking Dispersion

daysAbs %>% group_by(prog) %>% 
  summarize(MEAN  = mean(daysabs),
            VAR = var(daysabs),
            SD = sd(daysabs))

```

```{r}
# Old Code - reporting tool

with(daysAbs, tapply(daysabs, prog, function(x) {
    sprintf("Mean (SD) = %1.2f (%1.2f)", mean(x), sd(x))
}))

```

### Comparing Groups

```{r}
# Comparing Groups

# Overlaid histograms
ggplot(daysAbs, aes(x=daysabs, fill=prog)) +
    geom_histogram(binwidth=.5, alpha=.5, position="identity")
```

```{r}
# Interleaved histograms
ggplot(daysAbs, aes(x=daysabs, fill=prog)) +
    geom_histogram(binwidth=.5, position="dodge")
```

```{r}
# Density plots
ggplot(daysAbs, aes(x=daysabs, colour=prog)) + 
  geom_density(lwd=1.5) + 
  theme_bw()
  
```

```{r}
# Density plots with semi-transparent fill
ggplot(daysAbs, aes(x=daysabs, fill=prog)) + geom_density(alpha=.3)


```




```{r}
summary(m1 <- glm.nb(daysabs ~ math + prog, data = daysAbs))
```


```{r}
AIC(m1)
```
### Updated Model

```{r}
## math only
m2 <- update(m1, . ~ . - prog)
summary(m2)
```

```{r}
AIC(m2)
```
### Likelihood Ratio Test

Favour the model that uses both "math" and "prog"

```{r}
anova(m1, m2)
```

### Poisson Regression

```{r}
m3 <- glm(daysabs ~ math + prog, family = "poisson", data = daysAbs)
summary(m3)
```

```{r}
AIC(m3)
```


```{r}

#models are of different object classes, so LRT is harder to implement

pchisq(2 * (logLik(m1) - logLik(m3)), df = 1, lower.tail = FALSE)
```


### Model Estimates

```{r}

(est <- cbind(Estimate = coef(m1), confint(m1)))


exp(est)
```

### Contrived Data Set

```{r}
newdata1 <- data.frame(math = fivenum(daysAbs$math)[c(1,3,5)], 
		       prog = factor(1:3, levels = 1:3, 
		                     labels = levels(daysAbs$prog)))
```

```{r}
predict(m1, newdata1)
```

```{r}
newdata1$phat <- predict(m1, newdata1, type = "response")
newdata1

```

### Another Prediction

```{r}
newdata2 <- data.frame(
  math = rep(seq(from = min(daysAbs$math), 
                 to = max(daysAbs$math), length.out = 100), 3),
  prog = factor(rep(1:3, each = 100), levels = 1:3, labels =
  levels(daysAbs$prog)))
```

```{r}
newdata2 <- cbind(newdata2, predict(m1, newdata2, type = "link", se.fit=TRUE))
newdata2 <- within(newdata2, {
  DaysAbsent <- exp(fit)
  LL <- exp(fit - 1.96 * se.fit)
  UL <- exp(fit + 1.96 * se.fit)
})
```

```{r}
ggplot(newdata2, aes(math, DaysAbsent)) +
  geom_ribbon(aes(ymin = LL, ymax = UL, fill = prog), alpha = .25) +
  geom_line(aes(colour = prog), size = 2) +
  labs(x = "Math Score", y = "Predicted Days Absent")
```