#### Inference Procedures: Confidence Interval 
* A confidence interval gives an estimated range of values which is likely to include an unknown population parameter, the estimated range being calculated from a given set of sample data.

* If independent samples are taken repeatedly from the same population, and a confidence interval calculated for each sample, then a certain percentage (confidence level) of the intervals will include the unknown population parameter. 

* Confidence intervals are usually calculated so that this percentage is 95%, but we can produce 90%, 99%, 99.9% (or whatever) confidence intervals for the unknown parameter. 

* The width of the confidence interval gives us some idea about how uncertain we are about the unknown parameter. 

* A very wide interval may indicate that more data should be collected before anything very definite can be said about the parameter.


myTrueMean <- sample(95:105,1)

# Dont Look !!

myPop <- rnorm(25000,myTrueMean,20)

mySamp <- sample(myPop,30)

t.test(mySamp,mu=100)

myTestObject <- t.test(mySamp,mu=100)

class(myTestObject)
names(myTestObject)

myTestObject$conf.int

LL <- myTestObject$conf.int[1]
UL <- myTestObject$conf.int[2]

library(dplyr)

between(myTrueMean,LL,UL)


myResult <- numeric()

for (i in 1:10000){
 mySamp <- sample(myPop,30)
 myTestObject <- t.test(mySamp,mu=100)
 LL <- myTestObject$conf.int[1]
 UL <- myTestObject$conf.int[2]
 myResult <- c(myResult, between(myTrueMean,LL,UL) )
}