

% Load any packages needed for this document


## Residual Analysis for GLMs (Optional Section)}





###Pearson and Deviance Residuals()</tt>
% https://v8doc.sas.com/sashtml/insight/chap39/sect55.htm

Pearson Residuals





The Pearson residual is the raw residual divided by the square root of the variance function $V(\mu).$
The Pearson residual is the individual contribution to the Pearson $\chi^2$ statistic. 

For a binomial distribution with mi trials in the ith observation, it is defined as

\[ r_{Pi()</tt>= \sqrt{ m_{i}}
 \frac{r_{i}}{\sqrt{V(\hat{ \mu_{i}})}()</tt>\]
For other distributions, the Pearson residual is defined as

\[ r_{Pi()</tt>= \frac{r_{i}}{\sqrt{V(\hat{ \mu_{i}})}}\]
The Pearson residuals can be used to check the model fit at each observation for generalized linear models. 
%These residuals are stored in variables named RP_yname for each response variable, where yname is the response variable name. 
The standardized and studentized Pearson residuals are
\[
r_{Psi()</tt>= \frac{r_{Pi}}{\sqrt{\hat{ \phi()</tt>(1- h_{i})()</tt>()</tt>\]
\[ r_{Pti()</tt>= \frac{r_{Pi}}{\sqrt{ \hat{ \phi}_{(1. }
 (1- h_{i})()</tt>()</tt>\]



The \textbf{deviance residual()</tt>is the measure of deviance contributed from each observation and is given by
\[r_{Di()</tt>= \textrm{sign}( r_{i})
 \sqrt{ d_{i}}\]
where $d_i$ is the individual deviance contribution.
The deviance residuals can be used to check the model fit at each observation for generalized linear models. 

%These residuals are stored in variables named \textit{RD\_yname()</tt>for each response variable, where yname is the response variable name. 

The standardized and studentized deviance residuals are
\[
r_{Dsi()</tt>= \frac{r_{Di}}{\sqrt{\hat{ \phi()</tt>(1- h_{i})()</tt>}\]
\[r_{Dti()</tt>= \frac{r_{Di}}{\sqrt{ \hat{ \phi}_{(1. }
 (1- h_{i})}}\]
 

 
###Diagnostics for Logistic Regression}

###Diagnostics for Poisson Regression}


