%---------------------------------------------------------------------- %
\newpage
\subsection{Anderson-Darling Test}
To implement the Anderson-Darling Test for Normality, one must first install the \textbf{\emph{nortest}} package.

\begin{framed}
\begin{verbatim}
library(nortest)
#Generate 100 normally distributed random numbers
set.seed(1234)
NormDat = rnorm(100)
ad.test(NormDat)
\end{verbatim}
\end{framed}
\subsection{Shapiro-Wilk Test}
The Shapiro-Wilk test is directly implementable, without loading any additional packages.

\begin{framed}
\begin{verbatim}
#Generate 100 normally distributed random numbers
set.seed(1234)
NormDat = rnorm(100)

shapiro.test(NormDat)
\end{verbatim}
\end{framed}
Sample output, using the randomly generated \texttt{NormDat} data set, is as follows:
\begin{framed}
\begin{verbatim}
> shapiro.test(NormDat)

        Shapiro-Wilk normality test

data:  NormDat
W = 0.9864, p-value = 0.4003
\end{verbatim}
\end{framed}
Here, the p-value is well above the 0.05 threshold. Hence we \textbf{fail to reject} the null hypothesis, and may proceed to treat the \texttt{NormDat} data set as normally distributed.
\newpage
\subsection{Graphical Procedures for Assessing Normality}
There are two useful graphical methods for determining whether a data set was normally distributed. The first is the histogram, which we have seen previously. If the histogram is reasonably bell-shaped, then the data can be assumed to be normally distributed. The relevant \texttt{R} command is \texttt{\textbf{hist()}}.


The second is the \textbf{\emph{quantile-quantile plot}} (or QQ-plot).
For assessing normality, we implement a qq-plot  using the \texttt{\textbf{qqnorm()}} function.

Additionally the command \texttt{\textbf{qqline()}} function adds a trendline to a normal quantile-quantile plot. If the data is normally distributed, then the points on the plot follow the trendline.

\begin{framed}
\begin{verbatim}
#Generate 100 normally distributed random numbers

NormDat = rnorm(100)

qqnorm(NormDat)
qqline(NormDat)
\end{verbatim}
\end{framed}

% Section 8 Testing Normality
\subsection{Transforming the Data}
\begin{itemize}
\item Sometimes when we get non-normal data, it may be possible that we can change the scale of our data i.e. transform it to get a normal distribution. 
\item One transformation that often (but not always) works for positively skewed data is the natural logarithm (ln) transformation.
\item In such a case, we work with the natural logarithms of the data set, rather than the data itself.
\end{itemize}

\begin{framed}
\begin{verbatim}
> set.seed(1919)
> X = rexp(30,rate=0.50)
> shapiro.test(X)

        Shapiro-Wilk normality test

data:  X
W = 0.8213, p-value = 0.0001646
> shapiro.test(log(X))

        Shapiro-Wilk normality test

data:  log(X)
W = 0.9402, p-value = 0.09206
\end{verbatim}
\end{framed}
\subsection*{Outliers}
\begin{itemize}
\item Another reason that the data may not be normally distributed is the presence of an outlier. 
\item We shall look at formal tests for outliers (such as the \textbf{Grubb's Outliers test}) later. 
\item Recall that boxplots can be used to detect potential outliers.
\end{itemize}


%------------------------------------------
\begin{slide}{The Shapiro Wilk normality test}
The Shapiro Wilk is another commonly used procedure used to test normality.
Again, the null hypothesis is that the data set is normally distributed.
```{r}
> x=rnorm(40)
> shapiro.test(x)

        Shapiro-Wilk normality test

data:  x
W = 0.9601, p-value = 0.1689
```
Here, the P-value is greater than 1\%. We fail to reject the null hypothesis.
\end{slide}

