---
title: "Mean Imputation with R"
subtitle: Data Science with R
author: DragonflyStats.github.io
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Demonstration of Mean Imputation with R


#### 1. Create a "True" Data set ####
```{r}
TrueX <- rnorm(100,100,15)
TrueX <- round(TrueX)
TrueX
```


#### 2. Summary and Confidence Interval ####
```{r}
summary(TrueX)
```
```{r}
t.test(TrueX,mu=100)
```

#### 3. Create a data set with some value missing ####

```{r}
# "part" for partial

index <- sample(1:100,10)
partX <- TrueX 
partX[index] <- NA

partX
```

#### 4. Summary and Confidence Interval ####

```{r}
summary(partX)
```

```{r}
t.test(partX,mu=100)
```

#### 5. Create an Imputation Value (mean or median) ####

```{r}
# Wrong
imputeValue <- median(partX)
```

```{r}
#Right
imputeValue <- mean(partX,na.rm=TRUE)
```

#### 6. Impute this value into the data ####

```{r}
imputedX <- partX

imputedX [is.na(imputedX)] <- imputeValue
```

#### 7. Summary and Confidence Interval ####

```{r}
summary(imputedX)
```


```{r}
t.test(imputedX,mu=100)
```
