---
title: "Types of regression"
subtitle: Advanced Regression Models
author: DragonflyStats.github.io
date: "Last updated: `r format(Sys.time(), '%B %d, %Y')`"
output:
  rmdformats::readthedown:
    toc_depth: 3
    use_bookdown: TRUE
    #code_folding: hide
    fig_caption: TRUE


html_document:
  fig_caption: yes
  theme: flatly #sandstone #spacelab #
  highlight: pygments
  number_sections: TRUE
  toc: TRUE
  toc_width: 40
  toc_depth: 2
  toc_float:
    smooth_scroll: FALSE


---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
```
  
```{r import_libraries, echo=FALSE, message=FALSE}
# library(conflicted)
library(tidyverse)
# library(scales)
# library(cowplot)
# library(magrittr)

# library(rlang)
# library(stringr)
# library(glue)
# library(purrr)
# library(furrr)
# library(arules)
# library(arulesViz)
# library(DT)
# library(tidygraph)
# library(rfm)
#source("lib_utils.R")
# resolve_conflicts(
#   c("magrittr", "rlang", "dplyr", "readr", "purrr", "ggplot2", "arules",
#     "Matrix", "DT")
# )

knitr::opts_chunk$set(
  tidy       = FALSE,
  cache      = FALSE,
  warning    = FALSE,
  message    = FALSE,
  fig.height =     8,
  fig.width  =    12
)

options(
  width = 90L,
  warn  = 1
)

#theme_set(theme_cowplot())
set.seed(1234)
#plan(multisession)
```



```{r chunks, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(VGAM)
```


Machine Learning - types of regression
========================================================

* Polynomial Regression
* Censored Regression
* Tobit Regression
* Deming Regression
* Piece-wise Regression
* Interval Regression

Polynomial Regression
==================================================

### Polynomial Regression


<pre><code>
Abs<-c(0.084, 0.183, 0.326, 0.464, 0.643 ,0.671,0.701)

Conc<-c(0.123, 0.288, 0.562, 0.921, 1.420,1.723,2.121)

plot(Conc,Abs)

fit1 = lm(Abs~Conc)

Conc.sq = Conc^2

fit2 = lm(Abs~Conc + Conc.sq)

summary(fit1)

summary(fit2)
</code></pre>