---
title: "MethComp Data Sets"
author: "KevinOBrien"
date: "20 September 2018"
output: html_document
---



``scint`` Relative renal function by Scintigraphy
==============================================

#### Description
Measurements of the relative kidney function (=renal function) for 111 patients. The percentage
of the total renal function present in the left kidney is determined by one reference method, DMSA
(static) and by one of two dynamic methods, DTPA or EC.

### Format
A data frame with 222 observations on the following 5 variables:

* meth Measurement method, a factor with levels DMSA, DTPA, EC.
* item Patient identification.
* y Percentage of total kidney function in the left kidney.
* age Age of the patient.
* sex Sex of the patient, a factor with levels F, M.

### Examples
```{r}
data(scint)
str(scint)
# Make a Bland-Altman plot for each of the possible comparisons:
par(mfrow=c(1,2),mgp=c(3,1,0)/1.6,mar=c(3,3,1,3))
BA.plot(scint,comp.levels=c(1,2),ymax=15,digits=1,cex=2)
BA.plot(scint,comp.levels=c(1,3),ymax=15,digits=1,cex=2)

```

### Source
F. C. Domingues, G. Y. Fujikawa, H. Decker, G. Alonso, J. C. Pereira, P. S. Duarte: Comparison
of Relative Renal Function Measured with Either 99mTc-DTPA or 99mTc-EC Dynamic Scintigraphies
with that Measured with 99mTc-DMSA Static Scintigraphy. International Braz J Urol Vol.
32 (4): 405-409, 2006
