---
title: "Other Types of Studies"
subtitle: "Method Comparison Studies"
author: DragonflyStats.github.io
bibliography: RPUBSMCS.bib
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Other Types of Studies
=============================

@lewis categorize method comparison studies into threedifferent types.  The key difference between the first two is
whether or not a <i>gold standard</i> method is used. 

In situations where one instrument or method is known to be `accurate and
precise', it is considered as the`gold standard' \citep{lewis}. 
A method that is not considered to be a gold standard is referred to
as an `approximate method'. In calibration studies they arereferred to a criterion methods and test methods respectively.

### 1. Calibration problems. 

The purpose is to establish a relationship between methods, one of which is an approximate method, the other a gold standard. The results of the approximate
method can be mapped to a known probability distribution of the
results of the gold standard @lewis1991. 

In such studies, the gold standard method and corresponding approximate method are
generally referred to a criterion method and test method
respectively. @BA83 make clear that their framework is
not intended for calibration problems.

### 2. Comparison problems. 

When two approximate methods, that use the same units of measurement, are to be
compared. This is the case which the Bland-Altman methodology is specfically intended for, and therefore it is the most relevant of
the three.

### 3. Conversion problems. 

When two approximate methods, that use different units of measurement, are to be
compared. This situation would arise when the measurement methodsuse 'different proxies', i.e different mechanisms of measurement.
@lewis deals specifically with this issue. In the context of this study, it is the least relevant of the three.

\citet[p.47]{DunnSEME} cautions that ***gold standards*** should not be
assumed to be error free. `It is of necessity a subjective decision when we come to decide that a particular method or
instrument can be treated as if it was a gold standard'. The clinician gold standard, the sphygmomanometer, is used as an example thereof. The sphygmomanometer <i>leaves considerable room for improvement</i> (@DunnSEME). @pizzi similarly addresses the issue of glod standards, <i>well-established gold standard may itself be imprecise or even unreliable</i>.

The NIST F1 Caesium fountain atomic clock is considered to be the gold standard when measuring time, and is the primary time and frequency standard for the United States. The NIST F1 is accurateto within one second per 60 million years \citep{NIST}. In even extreme cases, there must be an assumption of inaccuracy with gold standard systems.


Measurements of the interior of the human body are, by definition,
invasive medical procedures. The design of method must balance the
need for accuracy of measurement with the well-being of the
patient. This will inevitably lead to the measurement error as
described by \citet{DunnSEME}. The magnetic resonance angiogram,
used to measure internal anatomy, is considered to the gold
standard for measuring aortic dissection. Medical tests based upon
the angiogram are reported to have a false positive reporting rate
of 5\% and a false negative reporting rate of 8\% \citep{ACR}.


In literature they are, perhaps more accurately, referred to as `fuzzy gold standards' \citep{phelps}. Consequently when one of the methods is
essentially a fuzzy gold standard, as opposed to a `true' gold
standard, the comparison of the criterion and test methods should
be consider in the context of a comparison study, as well as of a
calibration study.




\citet{Aroy2015} discusses the importance of gold standards in the context of method comparison studies.
Currently the phrase `gold standard' describes the most accurate method of measurement available. No other criteria are set out. Further to \citet{DunnSEME}, various gold standards have a varying levels of repeatability. Dunn cites the example of the sphygmomanometer (i.e. a blood pressure measurement cuff), which is prone to measurement error. Consequently it can be said that a measurement method can be the `gold standard', yet have poor repeatability. \citet{DunnSEME} recognizes this problem. Hence, if the most accurate method is considered to have poor repeatability, it is referred to as a `bronze standard'.  Again, no formal definition of a bronze standard exists.

% % % Bronze Standard


\citet[p.47]{DunnSEME} cautions that `gold standards' should not be
assumed to be error free and that `it is of necessity a subjective
decision when we come to decide that a particular method or
instrument can be treated as if it was a gold standard'. The
clinician gold standard, the sphygmomanometer, is used as an
example thereof.  The sphygmomanometer `leaves considerable room
for improvement'. \citet{pizzi} similarly
addresses the issue of gold standards, `well-established gold
standard may itself be imprecise or even unreliable'.




In literature gold standards are, perhaps more accurately, can be referred to as
`fuzzy gold standards' \citep{phelps}. Consequently, when one of the methods is
essentially a fuzzy gold standard, as opposed to a `true' gold standard, the comparison of the criterion and test methods should
be consider both in the context of a comparison study and acalibration study.


According to Bland and Altman, one should use the approach previous outlined, even when one of the methods is a gold standard.


---------------------------------------------

\section{Other Types of Studies}
\citet{lewis} categorize method comparison studies into three
different types.  The key difference between the first two is
whether or not a `gold standard' method is used. In situations
where one instrument or method is known to be `accurate and
precise', it is considered as the`gold standard' \citep{lewis}. A
method that is not considered to be a gold standard is referred to
as an `approximate method'. In calibration studies they are
referred to a criterion methods and test methods respectively.


\textbf{1. Calibration problems}. The purpose is to establish a
relationship between methods, one of which is an approximate
method, the other a gold standard. The results of the approximate
method can be mapped to a known probability distribution of the
results of the gold standard \citep{lewis}. (In such studies, the
gold standard method and corresponding approximate method are
generally referred to a criterion method and test method
respectively.) \citet*{BA83} make clear that their methodology is
not intended for calibration problems.

\bigskip \textbf{2. Comparison problems}. When two approximate
methods, that use the same units of measurement, are to be
compared. This is the case which the Bland-Altman methodology is
specfically intended for, and therefore it is the most relevant of
the three.



\bigskip \textbf{3. Conversion problems}. When two approximate
methods, that use different units of measurement, are to be
compared. This situation would arise when the measurement methods
use 'different proxies', i.e different mechanisms of measurement.
\citet{lewis} deals specifically with this issue. In the context
of this study, it is the least relevant of the three.
	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
	
	

	\section{Fuzzy Gold Standards} The Gold Standard is considered to be the most
	accurate measurement of a particular parameter. But even gold
	standard raters must be assumed to have some level of measurement
	error. Fuzzy gold standard are considered by Phelps and Hutson (
	1994)
	
\citet[p.47]{DunnSEME} cautions that`gold standards' should not be
assumed to be error free. `It is of necessity a subjective
decision when we come to decide that a particular method or
instrument can be treated as if it was a gold standard'. The
clinician gold standard , the sphygmomanometer, is used as an
example thereof.  The sphygmomanometer `leaves considerable room
for improvement' \citep{DunnSEME}. \citet{pizzi} similarly
addresses the issue of glod standards, `well-established gold
standard may itself be imprecise or even unreliable'.


The NIST F1 Caesium fountain atomic clock is considered to be the
gold standard when measuring time, and is the primary time and
frequency standard for the United States. The NIST F1 is accurate
to within one second per 60 million years \citep{NIST}.

Measurements of the interior of the human body are, by definition,
invasive medical procedures. The design of method must balance the
need for accuracy of measurement with the well-being of the
patient. This will inevitably lead to the measurement error as
described by \citet{DunnSEME}. The magnetic resonance angiogram,
used to measure internal anatomy,  is considered to the gold
standard for measuring aortic dissection. Medical test based upon
the angiogram is reported to have a false positive reporting rate
of 5\% and a false negative reporting rate of 8\%. This is
reported as sensitivity of 95\% and a specificity of 92\%
\citep{ACR}.

In literature they are, perhaps more accurately, referred to as
`fuzzy gold standards' \citep{phelps}. Consequently when one of the methods is
essentially a fuzzy gold standard, as opposed to a `true' gold
standard, the comparison of the criterion and test methods should
be consider in the context of a comparison study, as well as of a
calibration study.


	
	
	
	\citet{DunnSEME} makes two important points in relation to these
	categories. Firstly he remarks that there isn't clear cut differences between each category.
	
	Secondly he comments on the clinician gold standard, the
	sphygmomanometer, \emph{leaves considerable room for improvement}.
	\citet{pizzi} also attends to this issue: \emph{well-established
		gold standard may itself be imprecise or even unreliable}.
	
	The Magnetic resonance angiogram is considered to the gold
	standard for measuring aortic dissection, with a sensitivity of
	95\% and a specificity of 92\% . \citep{ACR}
	
	In literature they are, perhaps more accurately, referred to as 'bronze standards'.
	
	Consequently when one of the methods is essentially a bronze
	standard, as opposed to a true gold standard, the comparison
	procedure should be considered as being of the second category.
	
# References

<div id="refs"></div>