---
title: "vcd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(vcd)
```
* Package 'vcd'
* December 6, 2017
* Version 1.4-4
* Title Visualizing Categorical Data

#### Desription
Visualization techniques, data sets, summary and inference procedures aimed particularly at categorical data. Special emphasis is given to highly extensible grid graphics. The package was package was originally inspired by the book ``Visualizing Categorical Data'' by * Michael Friendly and is now the main support package for a new book,``Discrete Data Analysis with R'' by * Michael Friendly and
David Meyer (2015).

* LazyLoad yes
* LazyData yes
* Depends R (>= 2.4.0), grid
* Suggests KernSmooth, mvtnorm, kernlab, HSAUR, coin
* Imports stats, utils, MASS, grDevices, colorspace, lmtest
* License GPL-2
* NeedsCompilation no

#### Author 
* David Meyer [aut, cre],
* Achim Zeileis [aut] (<https://orcid.org/0000-0003-0918-3766>),
* Kurt Hornik [aut],
* Florian Gerber [ctb],
* Michael Friendly [ctb]

Maintainer David Meyer <David.Meyer@R-project.org>
Repository CRAN
Date/Publication 2017-12-06 10:51:14 UTC

